import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';


import { AuthProvider } from '@/src/contexts/AuthContext';
import { LayoutWrapper } from '@/src/components/Layout/LayoutWrapper';
import PageTransition from '@/src/components/ui/PageTransition';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Venda Facil - Controle de Vendas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased font-sans bg-gray-50  ${geistSans.variable} ${geistMono.variable}`}>

        <AuthProvider>
          <LayoutWrapper>
            <PageTransition>
              {children}
            </PageTransition>

          </LayoutWrapper>
        </AuthProvider>

      </body>
    </html>
  );
}
