import type { Metadata } from 'next';
import { Plus_Jakarta_Sans, IBM_Plex_Mono } from 'next/font/google';
import './globals.css';


import { AuthProvider } from '@/src/contexts/AuthContext';
import { LayoutWrapper } from '@/src/components/Layout/LayoutWrapper';
import PageTransition from '@/src/components/ui/PageTransition';

const plusJakarta = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Venda Facil - Controle de Vendas',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased font-sans bg-appbg text-ink ${plusJakarta.variable} ${ibmPlexMono.variable}`}>

        <AuthProvider>
          <LayoutWrapper>
            <PageTransition>
              {children}
            </PageTransition>

          </LayoutWrapper>
        </AuthProvider>

      </body>
    </html>
  );
}
